const $=s=>document.querySelector(s);const API={status:'/api/status?lite=1&pair=XAUUSD247',health:'/api/bridge-health',analyze:tf=>'/api/analyze?symbol=XAUUSD247&tf='+tf};function clock(){document.querySelector('#clock').textContent=new Intl.DateTimeFormat('en-MY',{timeZone:'Asia/Kuala_Lumpur',dateStyle:'medium',timeStyle:'medium',hour12:false}).format(new Date())+' MYT'}setInterval(clock,1000);clock();
async function j(url){const c=new AbortController();setTimeout(()=>c.abort(),8000);const r=await fetch(url,{cache:'no-store',signal:c.signal});if(!r.ok)throw Error(r.status);return r.json()}
function validQuote(x){return x&&x.ok===true&&x.bridgeOnline===true&&x.symbol==='XAUUSD247'&&x.source==='MT5_BROKER_TICK'}
function pick(o,...ks){for(const k of ks){if(o&&o[k]!=null)return o[k]}return null}
function dir(a){const raw=String(pick(a,'direction','bias','signal','trend')||pick(a?.analysis,'direction','bias','signal','trend')||'WAIT').toUpperCase();return raw.includes('SELL')||raw.includes('DOWN')||raw.includes('BEAR')?'SELL':raw.includes('BUY')||raw.includes('UP')||raw.includes('BULL')?'BUY':'WAIT'}
function renderTF(tf,a){const d=dir(a);return '<div class="tfrow">'+tf+' <b style="color:'+(d==='BUY'?'#30e08f':d==='SELL'?'#ff5570':'#ffc857')+'">'+d+'</b></div>'}
async function refresh(){let q,m15,h1;try{[q,m15,h1]=await Promise.all([j(API.status),j(API.analyze('M15')),j(API.analyze('H1'))])}catch(e){}
if(validQuote(q)){const bid=Number(q.bid),ask=Number(q.ask);$('#price').textContent=bid.toFixed(2)+' / '+ask.toFixed(2);const age=pick(q,'sampleAgeSeconds','ageSeconds');$('#fresh').textContent='MT5_BROKER_TICK • '+(age??'?')+'s old';$('#bridgeDot').textContent='● LIVE';$('#bridgeDot').style.color='#30e08f'}else{$('#price').textContent='BROKER UNAVAILABLE';$('#fresh').textContent='No public spot fallback';$('#bridgeDot').textContent='● OFFLINE';$('#bridgeDot').style.color='#ff5570'}
const ready=a=>a&&a.ok!==false&&a.ready!==false&&(!a.symbol||a.symbol==='XAUUSD247');const d15=ready(m15)?dir(m15):'WAIT',d1=ready(h1)?dir(h1):'WAIT';const bias=d15===d1?d15:'WAIT';$('#bias').textContent=bias;$('#bias').className='bias '+bias.toLowerCase();$('#confidence').textContent=pick(m15,'confidence','score')||pick(m15?.analysis,'confidence','score')||'—';$('#why').textContent=bias==='WAIT'?'M15/H1 belum sehaluan atau data belum lengkap. Tunggu confirmation broker candle.':('M15 dan H1 sehaluan '+bias+'. Entry hanya selepas confirmation/retest; jangan chase.');
$('#mtf').innerHTML=renderTF('M5',{bias:'WAIT'})+renderTF('M15',m15)+renderTF('H1',h1)+renderTF('H4',{bias:'WAIT'});$('#goldImpact').textContent='Gold: '+(bias==='SELL'?'cenderung tertekan':bias==='BUY'?'cenderung naik':'neutral / whipsaw');}
refresh();setInterval(refresh,15000);