const CFG={
  minValidScore:70,confirmWithin:8,maxValidAge:48,maxTouches:2,locationLookback:20,liquidityLookback:8,doubleLookback:35,
  doubleToleranceATR:.35,levelToleranceATR:.20,confirmBufferATR:.03,invalidBufferATR:.08,deleteAfterMoveATR:3,maxSignalRangeATR:2.5,
  atrPeriod:14,pressureLookback:20,minZonePressure:5.8,strongPressure:6.5,
  sndBaseMaxATR:1.0,sndDepartureMinATR:1.2,sndDepartureBodyRatio:.55,sndMaxAge:120,sndMaxTouches:2
};
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const norm=xs=>(xs||[]).map(x=>({t:num(x.t??x.time),o:num(x.o??x.open),h:num(x.h??x.high),l:num(x.l??x.low),c:num(x.c??x.close),v:num(x.v??x.tick_volume??x.volume)})).filter(x=>x.t&&x.h>=x.l&&x.o&&x.c).sort((a,b)=>a.t-b.t);
const range=b=>b.h-b.l,body=b=>Math.abs(b.c-b.o),top=b=>Math.max(b.o,b.c),bottom=b=>Math.min(b.o,b.c);
function tr(a,i){if(i<0||i>=a.length)return 0;let v=a[i].h-a[i].l;if(i>0){v=Math.max(v,Math.abs(a[i].h-a[i-1].c),Math.abs(a[i].l-a[i-1].c));}return v}
function atr(a,i,p=CFG.atrPeriod){let s=0,n=0;for(let j=Math.max(0,i-p+1);j<=i;j++){s+=tr(a,j);n++}return n?s/n:0}
function ema(a,i,p){if(i<0||!a.length)return 0;const start=Math.max(0,i-Math.max(p*4,p+5));let e=a[start].c,k=2/(Math.max(2,p)+1);for(let j=start+1;j<=i;j++)e=k*a[j].c+(1-k)*e;return e}
function highest(a,s,e){let v=-Infinity;for(let i=Math.max(0,s);i<=Math.min(e,a.length-1);i++)v=Math.max(v,a[i].h);return Number.isFinite(v)?v:0}
function lowest(a,s,e){let v=Infinity;for(let i=Math.max(0,s);i<=Math.min(e,a.length-1);i++)v=Math.min(v,a[i].l);return Number.isFinite(v)?v:0}
function pivotHigh(a,i,w=2){if(i-w<0||i+w>=a.length)return false;for(let k=1;k<=w;k++)if(a[i].h<=a[i-k].h||a[i].h<a[i+k].h)return false;return true}
function pivotLow(a,i,w=2){if(i-w<0||i+w>=a.length)return false;for(let k=1;k<=w;k++)if(a[i].l>=a[i-k].l||a[i].l>a[i+k].l)return false;return true}
function structureDirection(a,i){let rh=-1,oh=-1,rl=-1,ol=-1;for(let x=i-2;x>=2;x--){if(rh<0&&pivotHigh(a,x,2))rh=x;else if(rh>=0&&oh<0&&pivotHigh(a,x,2))oh=x;if(rl<0&&pivotLow(a,x,2))rl=x;else if(rl>=0&&ol<0&&pivotLow(a,x,2))ol=x;if(oh>=0&&ol>=0)break}if([rh,oh,rl,ol].some(x=>x<0))return 0;const higher=a[rh].h>a[oh].h&&a[rl].l>a[ol].l,lower=a[rh].h<a[oh].h&&a[rl].l<a[ol].l;return higher?1:lower?-1:0}
function trendDirection(a,time=Infinity){let i=a.length-2;while(i>5&&a[i].t>=time)i--;if(i<55)return 0;const e20=ema(a,i,20),e50=ema(a,i,50);let ma=a[i].c>e20&&e20>e50?1:a[i].c<e20&&e20<e50?-1:0;const st=structureDirection(a,i);return ma===st?ma:st===0?ma:ma===0?st:0}
function bullishEngulf(a,i){if(i<1)return false;const c=a[i],p=a[i-1];return c.c>c.o&&p.c<p.o&&bottom(c)<=bottom(p)&&top(c)>=top(p)&&body(c)>body(p)*.9}
function bearishEngulf(a,i){if(i<1)return false;const c=a[i],p=a[i-1];return c.c<c.o&&p.c>p.o&&bottom(c)<=bottom(p)&&top(c)>=top(p)&&body(c)>body(p)*.9}
function hammer(b){const r=range(b);if(r<=0)return false;const bo=Math.max(body(b),r*.05),lw=Math.min(b.o,b.c)-b.l,uw=b.h-Math.max(b.o,b.c);return bo<=r*.42&&lw>=bo*1.7&&uw<=r*.30&&b.c>=b.l+r*.55}
function shooting(b){const r=range(b);if(r<=0)return false;const bo=Math.max(body(b),r*.05),uw=b.h-Math.max(b.o,b.c),lw=Math.min(b.o,b.c)-b.l;return bo<=r*.42&&uw>=bo*1.7&&lw<=r*.30&&b.c<=b.l+r*.45}
function doubleBottom(a,i,ar){const tol=ar*CFG.doubleToleranceATR;if(range(a[i])<=0||a[i].c<a[i].l+range(a[i])*.52)return null;for(let k=i-4;k>=Math.max(2,i-CFG.doubleLookback);k--){if(!pivotLow(a,k,2)||Math.abs(a[i].l-a[k].l)>tol)continue;const neck=highest(a,k+1,i-1),base=Math.max(a[i].l,a[k].l);if(neck-base>=ar*.6)return neck}return null}
function doubleTop(a,i,ar){const tol=ar*CFG.doubleToleranceATR;if(range(a[i])<=0||a[i].c>a[i].l+range(a[i])*.48)return null;for(let k=i-4;k>=Math.max(2,i-CFG.doubleLookback);k--){if(!pivotHigh(a,k,2)||Math.abs(a[i].h-a[k].h)>tol)continue;const neck=lowest(a,k+1,i-1),t=Math.min(a[i].h,a[k].h);if(t-neck>=ar*.6)return neck}return null}
function rbs(a,i,ar){const tol=ar*CFG.levelToleranceATR;for(let k=i-6;k>=Math.max(2,i-30);k--){if(!pivotHigh(a,k,2))continue;const level=a[k].h;let broken=false;for(let j=k+1;j<=i-2;j++){if(a[j].c>level+ar*.05){broken=true;break}}if(broken&&a[i].l<=level+tol&&a[i].c>level&&a[i].c>a[i].o)return level}return null}
function sbr(a,i,ar){const tol=ar*CFG.levelToleranceATR;for(let k=i-6;k>=Math.max(2,i-30);k--){if(!pivotLow(a,k,2))continue;const level=a[k].l;let broken=false;for(let j=k+1;j<=i-2;j++){if(a[j].c<level-ar*.05){broken=true;break}}if(broken&&a[i].h>=level-tol&&a[i].c<level&&a[i].c<a[i].o)return level}return null}
function bullFlag(a,i,ar){if(i<11)return false;const hi=highest(a,i-4,i-1),lo=lowest(a,i-4,i-1);return hi-lo<=ar*1.8&&(a[i-5].c-a[i-10].c)>=ar*1.8&&a[i].c>hi+ar*.03&&a[i].c>a[i].o}
function bearFlag(a,i,ar){if(i<11)return false;const hi=highest(a,i-4,i-1),lo=lowest(a,i-4,i-1);return hi-lo<=ar*1.8&&(a[i-10].c-a[i-5].c)>=ar*1.8&&a[i].c<lo-ar*.03&&a[i].c<a[i].o}
function consider(c,d,name,base,low,high,confirm,loc,sweep,cont){const quality=base+(loc?15:0)+(sweep?15:0)+(cont?10:0),old=c.found?c.base+(c.loc?15:0)+(c.sweep?15:0)+(c.cont?10:0):-1;if(!c.found||(c.d!==d&&quality>old))return {found:true,d,name,base,low,high,confirm,loc,sweep,cont};if(c.d!==d)return c;return {...c,name:c.name.includes(name)?c.name:c.name+" + "+name,base:Math.min(45,Math.max(c.base,base)+5),low:Math.min(c.low,low),high:Math.max(c.high,high),confirm:d>0?Math.max(c.confirm,confirm):Math.min(c.confirm,confirm),loc:c.loc||loc,sweep:c.sweep||sweep,cont:c.cont||cont}}
function detectCandidate(a,i){if(i<Math.max(CFG.doubleLookback+8,CFG.locationLookback+4,CFG.atrPeriod+4))return null;const ar=atr(a,i),rg=range(a[i]);if(ar<=0||rg<=0||rg>ar*CFG.maxSignalRangeATR)return null;const pl=lowest(a,i-CFG.locationLookback,i-1),ph=highest(a,i-CFG.locationLookback,i-1),sl=lowest(a,i-CFG.liquidityLookback,i-1),sh=highest(a,i-CFG.liquidityLookback,i-1);const nearS=a[i].l<=pl+ar*CFG.levelToleranceATR,nearR=a[i].h>=ph-ar*CFG.levelToleranceATR,sweepL=a[i].l<sl&&a[i].c>sl,sweepH=a[i].h>sh&&a[i].c<sh;let c={found:false};if(bullishEngulf(a,i))c=consider(c,1,"Bullish Engulfing",30,a[i].l,a[i].h,a[i].h,nearS,sweepL,false);if(bearishEngulf(a,i))c=consider(c,-1,"Bearish Engulfing",30,a[i].l,a[i].h,a[i].l,nearR,sweepH,false);if(hammer(a[i]))c=consider(c,1,"Hammer",25,a[i].l,a[i].h,a[i].h,nearS,sweepL,false);if(shooting(a[i]))c=consider(c,-1,"Shooting Star",25,a[i].l,a[i].h,a[i].l,nearR,sweepH,false);const db=doubleBottom(a,i,ar);if(db!=null)c=consider(c,1,"Double Bottom",35,a[i].l,a[i].h,db,true,sweepL,false);const dt=doubleTop(a,i,ar);if(dt!=null)c=consider(c,-1,"Double Top",35,a[i].l,a[i].h,dt,true,sweepH,false);const rl=rbs(a,i,ar);if(rl!=null)c=consider(c,1,"RBS Retest",35,a[i].l,a[i].h,a[i].h,true,sweepL,true);const sr=sbr(a,i,ar);if(sr!=null)c=consider(c,-1,"SBR Retest",35,a[i].l,a[i].h,a[i].l,true,sweepH,true);if(bullFlag(a,i,ar))c=consider(c,1,"Bull Flag Breakout",35,a[i].l,a[i].h,a[i].h,nearS,sweepL,true);if(bearFlag(a,i,ar))c=consider(c,-1,"Bear Flag Breakdown",35,a[i].l,a[i].h,a[i].l,nearR,sweepH,true);return c.found?c:null}
function pressure(a,i,t1,t2,tp){const look=Math.min(CFG.pressureLookback,i-1);if(look<5)return {buyScore:5,sellScore:5,state:"BALANCED / WAIT",volumeRatio:1};let av=0;for(let j=i-look;j<i;j++)av+=a[j].v;av/=look;const vr=av>0?a[i].v/av:1,b=a[i],rg=range(b),ar=atr(a,i);if(rg<=0||ar<=0)return {buyScore:5,sellScore:5,state:"BALANCED / WAIT",volumeRatio:vr};const br=clamp(body(b)/rg,0,1),cp=clamp((b.c-b.l)/rg,0,1),lw=clamp((Math.min(b.o,b.c)-b.l)/rg,0,1),uw=clamp((b.h-Math.max(b.o,b.c))/rg,0,1);let buy=1,sell=1;if(b.c>b.o)buy+=br*2;else if(b.c<b.o)sell+=br*2;buy+=cp+lw*1.2;sell+=(1-cp)+uw*1.2;const vb=clamp(vr-.5,0,1.5);if(b.c>b.o)buy+=vb;else if(b.c<b.o)sell+=vb;const mi=Math.max(0,i-3),mom=b.c-a[mi].c,mw=clamp(Math.abs(mom)/ar,0,1.5);if(mom>0)buy+=mw;else if(mom<0)sell+=mw;const lb=Math.min(10,i),ph=highest(a,i-lb,i-1),pl=lowest(a,i-lb,i-1);if(b.c>ph)buy+=1.5;else if(b.c<pl)sell+=1.5;if(t1>0)buy+=1.25;else if(t1<0)sell+=1.25;if(t2>0)buy+=1;else if(t2<0)sell+=1;if(tp>0)buy+=.75;else if(tp<0)sell+=.75;const total=buy+sell,bs=10*buy/total,ss=10*sell/total,diff=bs-ss;return {buyScore:bs,sellScore:ss,state:bs>=CFG.strongPressure&&diff>=1.5?"BUY STRONG":ss>=CFG.strongPressure&&diff<=-1.5?"SELL STRONG":diff>=.8?"BUY MODERATE":diff<=-.8?"SELL MODERATE":"BALANCED / WAIT",volumeRatio:vr}}
function score(z,t1,t2,tp,confirmed){let s=z.base+(z.loc?15:0)+(z.sweep?15:0)+(z.cont?10:0);if(t1===z.d)s+=15;if(t2===z.d)s+=10;if(tp===z.d)s+=5;if(confirmed)s+=10;return Math.min(100,s)}
function detectSND(a,i){if(i<8)return null;const ar=atr(a,i),rg=range(a[i]);if(ar<=0||rg<ar*CFG.sndDepartureMinATR||body(a[i])/rg<CFG.sndDepartureBodyRatio)return null;let cnt=0;for(let off=1;off<=3&&i-off>=0;off++){if(range(a[i-off])>ar*CFG.sndBaseMaxATR)break;cnt++}if(cnt<1)return null;let low=a[i-1].l,high=a[i-1].h,hBody=top(a[i-1]),lBody=bottom(a[i-1]);for(let off=2;off<=cnt;off++){const b=a[i-off];low=Math.min(low,b.l);high=Math.max(high,b.h);hBody=Math.max(hBody,top(b));lBody=Math.min(lBody,bottom(b))}if(a[i].c>a[i].o&&a[i].c>high+ar*.05)return {d:1,low,high:Math.max(low,hBody),label:"DEMAND"};if(a[i].c<a[i].o&&a[i].c<low-ar*.05)return {d:-1,low:Math.min(high,lBody),high,label:"SUPPLY"};return null}
function nearest(zs,p){return zs.slice().sort((a,b)=>Math.min(Math.abs(p-a.low),Math.abs(p-a.high))-Math.min(Math.abs(p-b.low),Math.abs(p-b.high)))[0]||null}
export function runPattern132({triggerBars,setupBars,biasBars,triggerTF,setupTF,biasTF,symbol,point=0}){
  const a=norm(triggerBars),t2a=norm(setupBars),t1a=norm(biasBars);if(a.length<100)return {ready:false,error:"Insufficient broker candles"};
  const zones=[],snd=[],hist=[];const start=Math.max(45,a.length-180);
  for(let i=start;i<a.length-1;i++){
    const closeT=a[i].t;const t1=trendDirection(t1a,closeT+1),t2=trendDirection(t2a,closeT+1),tp=trendDirection(a,closeT+1),ar=Math.max(atr(a,i),point*20||1e-9),pr=pressure(a,i,t1,t2,tp);
    for(let z=zones.length-1;z>=0;z--){const q=zones[z];q.age++;const invalid=q.d>0?a[i].c<q.low-ar*CFG.invalidBufferATR:a[i].c>q.high+ar*CFG.invalidBufferATR;if(invalid){zones.splice(z,1);continue}if(q.state==="WATCH"){const confirmed=q.d>0?(a[i].c>q.confirm+ar*CFG.confirmBufferATR&&a[i].c>a[i].o):(a[i].c<q.confirm-ar*CFG.confirmBufferATR&&a[i].c<a[i].o);if(confirmed)q.confirmed=true;q.score=score(q,t1,t2,tp,q.confirmed);const dp=q.d>0?pr.buyScore:pr.sellScore;if(q.confirmed&&(q.loc||q.sweep||q.cont)&&dp>=CFG.minZonePressure&&q.score>=CFG.minValidScore){q.state="VALID";q.confirmedTime=a[i].t;q.pressure=dp;hist.push({time:a[i].t,direction:q.d,code:q.d>0?"B":"S",score:q.score,entry:a[i].c,invalidation:q.d>0?q.low-ar*CFG.invalidBufferATR:q.high+ar*CFG.invalidBufferATR,tp1:null,tp2:null,status:"VALID",outcome:0,reasons:[q.name,"PATTERN CONFIRMED",pr.state]});}else if(q.age>CFG.confirmWithin){zones.splice(z,1);continue}}else{if(q.age>CFG.maxValidAge){zones.splice(z,1);continue}const ov=a[i].l<=q.high&&a[i].h>=q.low;if(a[i].t>q.confirmedTime){if(ov&&!q.inside)q.touches++;q.inside=ov}if(q.touches>=CFG.maxTouches){zones.splice(z,1);continue}const far=q.d>0?a[i].c>q.high+ar*CFG.deleteAfterMoveATR:a[i].c<q.low-ar*CFG.deleteAfterMoveATR;if(far){zones.splice(z,1);continue}}}
    for(let z=snd.length-1;z>=0;z--){const q=snd[z];q.age++;const invalid=q.d>0?a[i].c<q.low-ar*CFG.invalidBufferATR:a[i].c>q.high+ar*CFG.invalidBufferATR;if(invalid||q.age>CFG.sndMaxAge){snd.splice(z,1);continue}const ov=a[i].l<=q.high&&a[i].h>=q.low;if(a[i].t>q.created){if(ov&&!q.inside)q.touches++;q.inside=ov}if(q.touches>=CFG.sndMaxTouches){snd.splice(z,1);continue}}
    const c=detectCandidate(a,i);if(c&&!zones.some(z=>z.created===a[i].t&&z.d===c.d))zones.push({...c,created:a[i].t,state:"WATCH",age:0,touches:0,inside:false,confirmed:false,confirmedTime:0,score:score(c,t1,t2,tp,false)});
    const sz=detectSND(a,i);if(sz&&!snd.some(z=>Math.abs(((z.low+z.high)/2)-((sz.low+sz.high)/2))<=ar*.2&&z.d===sz.d))snd.push({...sz,created:a[Math.max(0,i-1)].t,age:0,touches:0,inside:false,score:60});
  }
  const last=a.at(-2)||a.at(-1),price=last?.c||0,t1=trendDirection(t1a),t2=trendDirection(t2a),tp=trendDirection(a),pr=pressure(a,a.length-2,t1,t2,tp);
  const all=zones.concat(snd.map(z=>({...z,state:"SND",name:z.label,base:60,score:60})));const active=all.map(z=>({tf:triggerTF,direction:z.d,currentDirection:z.d,high:z.high,low:z.low,baseScore:z.score||z.base||60,sourceEvent:(z.state||"")+" "+(z.name||z.label||"ZONE"),swapped:false,currentRetests:z.touches||0,state:z.state}));
  const buy=active.filter(z=>z.direction>0).slice(-5).reverse(),sell=active.filter(z=>z.direction<0).slice(-5).reverse();const n=nearest(active,price);
  const latest=hist.at(-1)||{code:"WAIT",score:0,status:"WAIT PATTERN VALIDATION",reason:"YELLOW WATCH -> CONFIRM -> PRESSURE FILTER"};
  const stats={total:hist.length,tp:0,tr:0,be:0,sl:0,pending:hist.length,wins:0,losses:0,winRate:0};
  return {ready:true,engine:"XAU_Pattern_Zone_Tutor_v1.32 web port • dynamic multi-asset",symbol,profile:{triggerTF,setupTF,biasTF},setupState:{trend:t2,strength:50+Math.abs(pr.buyScore-pr.sellScore)*5,lastEvent:"PRESSURE "+pr.state},biasState:{trend:t1,strength:50,lastEvent:"AUTO TREND"},premiumDiscount:null,activeZones:{buy,sell,swap:[]},latestSignal:latest,watch:n?{direction:n.direction,distance:Math.min(Math.abs(price-n.low),Math.abs(price-n.high)),zone:{low:n.low,high:n.high},reason:n.sourceEvent}:null,history:hist.slice(-160),stats,pressure:pr};
}
