const TFSEC={M1:60,M5:300,M15:900,M30:1800,H1:3600,H4:14400,D1:86400,W1:604800,MN1:2592000};
const RULES={
 M1:{wing:3,base:3,touches:3,dep:1.8,max:.7},M5:{wing:3,base:4,touches:2,dep:1.5,max:.9},M15:{wing:4,base:4,touches:2,dep:1.3,max:1},M30:{wing:4,base:5,touches:2,dep:1.2,max:1.1},H1:{wing:4,base:5,touches:2,dep:1.1,max:1.2},H4:{wing:5,base:6,touches:2,dep:1,max:1.3},D1:{wing:5,base:6,touches:2,dep:.9,max:1.5}
};
const CFG={atr:14,merge:.2,breakout:.1,retest:.2,invalid:.1,maxRetests:2,minZoneScore:60,priorSwing:50,minM1Score:50,maxAfter:5,m1Struct:3,m1Sweep:5,minWick:.20,minRejectClose:.50,minClose:.60,minBody:.25,m1Break:.02,m1EarlyInvalid:.10,strong:75};
const num=v=>Number.isFinite(Number(v))?Number(v):0,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const norm=xs=>(xs||[]).map(x=>({t:num(x.t??x.time),o:num(x.o??x.open),h:num(x.h??x.high),l:num(x.l??x.low),c:num(x.c??x.close),v:num(x.v??x.tick_volume??x.volume)})).filter(x=>x.t&&x.h>=x.l&&x.o&&x.c).sort((a,b)=>a.t-b.t);
const range=b=>b.h-b.l,body=b=>Math.abs(b.c-b.o),top=b=>Math.max(b.o,b.c),bottom=b=>Math.min(b.o,b.c),directional=(b,d)=>d>0?b.c>b.o:b.c<b.o;
function tr(a,i){let v=a[i].h-a[i].l;if(i>0)v=Math.max(v,Math.abs(a[i].h-a[i-1].c),Math.abs(a[i].l-a[i-1].c));return v}
function atr(a,i,p=CFG.atr){let s=0,n=0;for(let j=Math.max(0,i-p+1);j<=i;j++){s+=tr(a,j);n++}return n?s/n:0}
function highest(a,s,e){let v=-Infinity;for(let i=Math.max(0,s);i<=Math.min(e,a.length-1);i++)v=Math.max(v,a[i].h);return Number.isFinite(v)?v:0}
function lowest(a,s,e){let v=Infinity;for(let i=Math.max(0,s);i<=Math.min(e,a.length-1);i++)v=Math.min(v,a[i].l);return Number.isFinite(v)?v:0}
function pivotHigh(a,i,w){if(i-w<0||i+w>=a.length)return false;for(let k=1;k<=w;k++)if(a[i].h<=a[i-k].h||a[i].h<a[i+k].h)return false;return true}
function pivotLow(a,i,w){if(i-w<0||i+w>=a.length)return false;for(let k=1;k<=w;k++)if(a[i].l>=a[i-k].l||a[i].l>a[i+k].l)return false;return true}
function engulf(a,i,d){if(i<1)return false;const c=a[i],p=a[i-1];if(!directional(c,d)||directional(p,d))return false;return bottom(c)<=bottom(p)&&top(c)>=top(p)}
function volumeRatio(a,s,e,priorStart,count){let cur=0,n=0;for(let i=s;i<=e&&i<a.length;i++){cur+=a[i].v;n++}cur=n?cur/n:0;let av=0,k=0;for(let i=priorStart;i>=0&&k<count;i--,k++)av+=a[i].v;av=k?av/k:0;return av>0?cur/av:1}
function priorPivot(a,start,end,w,high){for(let i=Math.min(end,a.length-w-1);i>=Math.max(w,start);i--){if(high?pivotHigh(a,i,w):pivotLow(a,i,w))return high?a[i].h:a[i].l}return null}
function duplicate(zs,mid,tol,d,type){return zs.some(z=>z.d===d&&z.type===type&&Math.abs((z.low+z.high)/2-mid)<=tol)}
function countRetests(a,start,high,low,d,inv){let ret=0,inside=false,endTime=0;for(let i=start;i<a.length-1;i++){const fail=d>0?a[i].c<low-inv:a[i].c>high+inv;if(fail){endTime=a[i].t;break}const ov=a[i].l<=high&&a[i].h>=low;if(ov&&!inside)ret++;inside=ov}return {ret,endTime}}
function scanSND(a,tf){const cfg=RULES[tf]||RULES.M5,zs=[];const maxEnd=a.length-3;for(let baseNewest=cfg.wing+10;baseNewest<=maxEnd;baseNewest++){
  for(let len=1;len<=cfg.base;len++){
    const baseOld=baseNewest-len+1;if(baseOld<cfg.wing+3)break;const ar=Math.max(atr(a,baseNewest),1e-12);let bh=-Infinity,bl=Infinity,bbodyH=-Infinity,bbodyL=Infinity,valid=true;for(let i=baseOld;i<=baseNewest;i++){bh=Math.max(bh,a[i].h);bl=Math.min(bl,a[i].l);bbodyH=Math.max(bbodyH,top(a[i]));bbodyL=Math.min(bbodyL,bottom(a[i]));if(body(a[i])>range(a[i])*.60)valid=false}if(!valid||bh-bl>ar*cfg.max)continue;
    const d1=baseNewest+1,d2=baseNewest+2;if(d2>=a.length-1)continue;const impH=Math.max(a[d1].h,a[d2].h),impL=Math.min(a[d1].l,a[d2].l),buf=ar*CFG.breakout,priorEnd=Math.max(cfg.wing,baseOld-CFG.priorSwing),vr=volumeRatio(a,d1,d2,baseOld-1,Math.max(5,CFG.atr));
    const pH=priorPivot(a,priorEnd,baseOld-cfg.wing,cfg.wing,true),pL=priorPivot(a,priorEnd,baseOld-cfg.wing,cfg.wing,false);
    const bullFvg=a[d2].l>a[baseNewest].h,bearFvg=a[d2].h<a[baseNewest].l;
    const demHigh=bbodyH,demLow=bl,bullDisp=a[d2].c>demHigh&&(impH-demHigh)>=ar*cfg.dep,actualBos=pH!=null&&a[d2].c>pH+buf;
    if(bullDisp&&actualBos){const r=countRetests(a,d2+1,demHigh,demLow,1,ar*CFG.invalid);const score=25+25+15+(bullFvg?10:0)+(r.ret===0?20:10)+(vr>=1.2?5:0);const mid=(demHigh+demLow)/2;if(score>=CFG.minZoneScore&&r.ret<=CFG.maxRetests&&!duplicate(zs,mid,Math.max(ar*.3,1e-9),1,"DEMAND"))zs.push({type:"DEMAND",tf,d:1,low:demLow,high:demHigh,score,retests:r.ret,origin:a[baseOld].t,ready:a[d2].t+(TFSEC[tf]||60),end:r.endTime,source:"DEMAND"})}
    const supHigh=bh,supLow=bbodyL,bearDisp=a[d2].c<supLow&&(supLow-impL)>=ar*cfg.dep,actualBosD=pL!=null&&a[d2].c<pL-buf;
    if(bearDisp&&actualBosD){const r=countRetests(a,d2+1,supHigh,supLow,-1,ar*CFG.invalid);const score=25+25+15+(bearFvg?10:0)+(r.ret===0?20:10)+(vr>=1.2?5:0);const mid=(supHigh+supLow)/2;if(score>=CFG.minZoneScore&&r.ret<=CFG.maxRetests&&!duplicate(zs,mid,Math.max(ar*.3,1e-9),-1,"SUPPLY"))zs.push({type:"SUPPLY",tf,d:-1,low:supLow,high:supHigh,score,retests:r.ret,origin:a[baseOld].t,ready:a[d2].t+(TFSEC[tf]||60),end:r.endTime,source:"SUPPLY"})}
  }
 }
 return zs.slice(-80);
}
function pivotClusters(a,tf){const cfg=RULES[tf]||RULES.M5,zs=[];for(const highSide of [true,false]){const piv=[];for(let i=cfg.wing;i<a.length-cfg.wing-1;i++){if(highSide?pivotHigh(a,i,cfg.wing):pivotLow(a,i,cfg.wing))piv.push(i)}for(let s=0;s<piv.length;s++){const i=piv[s],ar=Math.max(atr(a,i),1e-12),tol=ar*CFG.merge,seed=highSide?a[i].h:a[i].l,grp=piv.filter(j=>Math.abs((highSide?a[j].h:a[j].l)-seed)<=tol);if(grp.length<cfg.touches)continue;const level=grp.reduce((sum,j)=>sum+(highSide?a[j].h:a[j].l),0)/grp.length,newest=Math.max(...grp),oldest=Math.min(...grp);let br=-1;for(let j=newest+1;j<a.length-1;j++){if(highSide&&a[j].c>level+ar*CFG.breakout&&a[j-1].c<=level+ar*CFG.breakout){br=j;break}if(!highSide&&a[j].c<level-ar*CFG.breakout&&a[j-1].c>=level-ar*CFG.breakout){br=j;break}}
      const dupTol=Math.max(tol*.75,1e-9);if(br<0){const type=highSide?"RESISTANCE":"SUPPORT",d=highSide?-1:1;if(!duplicate(zs,level,dupTol,d,type))zs.push({type,tf,d,low:level-tol,high:level+tol,score:60,retests:grp.length,origin:a[oldest].t,ready:a[newest].t+(TFSEC[tf]||60),end:0,source:type})}
      else{const type=highSide?"RBS":"SBR",d=highSide?1:-1;let ret=0,inside=false,end=0;for(let j=br+1;j<a.length-1;j++){const fail=d>0?a[j].c<level-ar*CFG.invalid:a[j].c>level+ar*CFG.invalid;if(fail){end=a[j].t;break}const ov=a[j].l<=level+tol&&a[j].h>=level-tol;if(ov&&!inside)ret++;inside=ov}if(ret<=CFG.maxRetests&&!duplicate(zs,level,dupTol,d,type))zs.push({type,tf,d,low:level-tol,high:level+tol,score:65,retests:ret,origin:a[br].t,ready:a[br].t+(TFSEC[tf]||60),end,source:type})}
    }}
 return zs.slice(-80);
}
function m5Trend(a,time,d){let idx=-1;for(let i=0;i<a.length;i++)if(a[i].t<time)idx=i;if(idx<6)return {support:false,against:false};let bull=0,bear=0;for(let i=Math.max(1,idx-3);i<=idx;i++){if(a[i].c>a[i].o)bull++;else if(a[i].c<a[i].o)bear++}const move=Math.abs(a[idx].c-a[Math.max(0,idx-4)].c),ar=Math.max(atr(a,idx),1e-12),dir=bull>=3&&a[idx].c>a[Math.max(0,idx-4)].c&&move>=ar*.8?1:bear>=3&&a[idx].c<a[Math.max(0,idx-4)].c&&move>=ar*.8?-1:0;return {support:dir===d,against:dir===-d}}
function htfReject(a,time,high,low,d){let i=-1;for(let j=0;j<a.length;j++)if(a[j].t<time)i=j;if(i<4)return null;const ar=Math.max(atr(a,i),1e-12),tol=ar*.10,b=a[i];if(!(b.l<=high+tol&&b.h>=low-tol))return null;const rg=range(b),wick=d>0?bottom(b)-b.l:b.h-top(b),loc=d>0?(b.c-b.l)/rg:(b.h-b.c)/rg;let prior=d>0?Infinity:-Infinity;for(let j=Math.max(0,i-3);j<i;j++)prior=d>0?Math.min(prior,a[j].l):Math.max(prior,a[j].h);const sweep=d>0?b.l<prior&&b.c>prior:b.h>prior&&b.c<prior,eng=engulf(a,i,d),rej=wick/rg>=.18&&loc>=.50;if(sweep)return "SWEEP";if(eng)return "ENGULF";if(rej)return "REJECT";return null}
function validTrigger(a,i,z,m5,m15){const ar=Math.max(atr(a,i),1e-12),b=a[i],rg=range(b);if(rg<=0)return null;const d=z.d,mid=(z.high+z.low)/2,midOK=d>0?b.c>=mid:b.c<=mid,st=d>0?highest(a,Math.max(0,i-CFG.m1Struct),i-1):lowest(a,Math.max(0,i-CFG.m1Struct),i-1),structure=d>0?b.c>st+ar*CFG.m1Break:b.c<st-ar*CFG.m1Break,eng=engulf(a,i,d),sw=d>0?lowest(a,Math.max(0,i-CFG.m1Sweep),i-1):highest(a,Math.max(0,i-CFG.m1Sweep),i-1),sweep=d>0?b.l<sw&&b.c>sw:b.h>sw&&b.c<sw,wick=d>0?bottom(b)-b.l:b.h-top(b),loc=d>0?(b.c-b.l)/rg:(b.h-b.c)/rg,rej=wick/rg>=CFG.minWick,rejTrigger=(rej&&loc>=CFG.minRejectClose)||sweep;if(!(structure||eng||rejTrigger))return null;if(!directional(b,d)&&!rejTrigger)return null;if(!midOK&&!rejTrigger)return null;const trend=m5Trend(m5,b.t+(TFSEC.M1||60),d);let score=25+(directional(b,d)?15:5)+(midOK?10:0),reasons=[];if(structure){score+=25;reasons.push("BOS/CHOCH")}if(eng){score+=20;reasons.push("ENGULF")}if(sweep){score+=12;reasons.push("SWEEP")}if(rej){score+=15;reasons.push("REJECT")}if(wick/rg>=.20&&loc>=CFG.minClose){score+=10;reasons.push("STRONG WICK")}if(body(b)>=ar*CFG.minBody&&loc>=CFG.minClose){score+=10;reasons.push("MOMENTUM")}if(trend.support){score+=10;reasons.push("M5 TREND ALIGN")}const r5=htfReject(m5,b.t+60,z.high,z.low,d),r15=htfReject(m15,b.t+60,z.high,z.low,d);if(r5){score+=10;reasons.push("M5 "+r5)}if(r15){score+=10;reasons.push("M15 "+r15)}if(trend.against){score-=10;reasons.push("M5 AGAINST")}score=clamp(score,0,100);return score>=CFG.minM1Score?{score,reasons}:null}
function scanSignals(m1,zones,m5,m15){const hist=[];for(const z of zones){let visit=false,signalled=false,left=false,after=0,count=0;let start=m1.findIndex(b=>b.t>=z.ready);if(start<1)start=1;for(let i=start;i<m1.length-1;i++){if(z.end&&m1[i].t>=z.end)break;const ar=Math.max(atr(m1,i),1e-12),inv=ar*CFG.m1EarlyInvalid;if(z.d>0?m1[i].c<z.low-inv:m1[i].c>z.high+inv)break;const touch=m1[i].l<=z.high+ar*.05&&m1[i].h>=z.low-ar*.05;if(touch){if(!visit||(signalled&&left)){visit=true;signalled=false}left=false;after=0}else if(visit){after++;if(signalled)left=true;if(after>CFG.maxAfter){visit=false;signalled=false;left=false;continue}}if(!visit||signalled||count>=3)continue;const v=validTrigger(m1,i,z,m5,m15);if(!v)continue;hist.push({time:m1[i].t,direction:z.d,code:z.d>0?(v.score>=CFG.strong?"B+":"B"):(v.score>=CFG.strong?"S+":"S"),score:v.score,entry:m1[i].c,invalidation:z.d>0?z.low-inv:z.high+inv,tp1:null,tp2:null,status:"VALID",outcome:0,reasons:[z.type+" "+z.tf].concat(v.reasons),zone:{low:z.low,high:z.high,tf:z.tf,source:z.type}});signalled=true;count++}}
 hist.sort((a,b)=>a.time-b.time);return hist.slice(-160)}
function trendState(a){const i=a.length-2;if(i<20)return {trend:0,strength:50,lastEvent:"STRUCTURE"};const e20=(()=>{let e=a[Math.max(0,i-80)].c,k=2/21;for(let j=Math.max(0,i-80)+1;j<=i;j++)e=k*a[j].c+(1-k)*e;return e})(),e50=(()=>{let e=a[Math.max(0,i-200)].c,k=2/51;for(let j=Math.max(0,i-200)+1;j<=i;j++)e=k*a[j].c+(1-k)*e;return e})();const d=e20>e50?1:e20<e50?-1:0,ar=Math.max(atr(a,i),1e-12);return {trend:d,strength:clamp(50+Math.abs(e20-e50)/ar*15,50,100),lastEvent:"STRICT TF STRUCTURE"}}
export function runSND107({triggerBars,setupBars,biasBars,m5Bars,m15Bars,triggerTF,setupTF,biasTF,symbol,point=0}){
 const m1=norm(triggerBars),src=norm(setupBars),ctx=norm(biasBars);if(m1.length<120||src.length<100)return {ready:false,error:"Insufficient broker candles"};const zones=scanSND(src,setupTF).concat(pivotClusters(src,setupTF));const active=zones.filter(z=>!z.end||z.end>=(src.at(-2)?.t||0)).map(z=>({tf:z.tf,direction:z.d,currentDirection:z.d,high:z.high,low:z.low,baseScore:z.score,sourceEvent:z.type,swapped:false,currentRetests:z.retests,state:"VALID"}));const m5=(m5Bars&&m5Bars.length)?norm(m5Bars):(setupTF==="M5"?src:ctx);const m15=(m15Bars&&m15Bars.length)?norm(m15Bars):(setupTF==="M15"?src:ctx);const hist=scanSignals(m1,zones,m5,m15);const latest=hist.at(-1)||{code:"WAIT",score:0,status:"WAIT M1 CONFIRMATION",reason:"STRICT TF AREA + M1 CLOSED-CANDLE CONFIRMATION"};const stats={total:hist.length,tp:0,tr:0,be:0,sl:0,pending:hist.length,wins:0,losses:0,winRate:0},last=m1.at(-2)||m1.at(-1),price=last?.c||0,sorted=active.slice().sort((a,b)=>Math.min(Math.abs(price-a.low),Math.abs(price-a.high))-Math.min(Math.abs(price-b.low),Math.abs(price-b.high))),watch=sorted[0]?{direction:sorted[0].direction,distance:Math.min(Math.abs(price-sorted[0].low),Math.abs(price-sorted[0].high)),zone:{low:sorted[0].low,high:sorted[0].high},reason:sorted[0].sourceEvent+" "+setupTF+" -> M1 CONFIRM"}:null;return {ready:true,engine:"Gold_SND_SNR_SBR_RBS_MTF_v1.07_STRICT_TF web port • dynamic multi-asset",symbol,profile:{triggerTF,setupTF,biasTF},setupState:trendState(src),biasState:trendState(ctx.length?ctx:src),premiumDiscount:null,activeZones:{buy:active.filter(z=>z.direction>0).slice(-8).reverse(),sell:active.filter(z=>z.direction<0).slice(-8).reverse(),swap:active.filter(z=>/RBS|SBR/.test(z.sourceEvent))},latestSignal:latest,watch,history:hist,stats};
}
