function num(v){const x=Number(v);return Number.isFinite(x)?x:null}
async function text(url,ms=7000){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,cache:"no-store"});if(!r.ok)throw new Error("HTTP "+r.status);return await r.text()}finally{clearTimeout(t)}}
async function json(url,ms=7000){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,cache:"no-store"});if(!r.ok)throw new Error("HTTP "+r.status);return await r.json()}finally{clearTimeout(t)}}
function xmlVal(e,k){const m=e.match(new RegExp("<d:"+k+"[^>]*>([^<]+)<\\/d:"+k+">","i"));return m?m[1]:null}
function parseTreasury(x,key){const rows=[...String(x).matchAll(/<entry>([\s\S]*?)<\/entry>/gi)].map(m=>m[1]).map(e=>({date:(xmlVal(e,"NEW_DATE")||"").slice(0,10),value:num(xmlVal(e,key))})).filter(x=>x.date&&x.value!==null).sort((a,b)=>a.date.localeCompare(b.date));return rows.at(-1)||null}
async function treasury(data,key){const d=new Date();const month=String(d.getUTCFullYear())+String(d.getUTCMonth()+1).padStart(2,"0");return parseTreasury(await text("https://home.treasury.gov/resource-center/data-chart-center/interest-rates/pages/xml?data="+data+"&field_tdr_date_value_month="+month),key)}
async function dxy(){try{const j=await json("https://query1.finance.yahoo.com/v8/finance/chart/DX-Y.NYB?interval=5m&range=5d");const q=j?.chart?.result?.[0]?.indicators?.quote?.[0]?.close||[];const v=[...q].reverse().find(x=>num(x)!==null);return num(v)}catch{return null}}
function parseCsvLast(s){const lines=String(s).trim().split(/\r?\n/);if(lines.length<2)return null;const h=lines[0].split(",");const iDate=h.findIndex(x=>/TIME_PERIOD|date/i.test(x));const iVal=h.findIndex(x=>/OBS_VALUE|value/i.test(x));for(let i=lines.length-1;i>0;i--){const c=lines[i].split(",");const v=num(c[iVal]);if(v!==null)return{date:c[iDate],value:v}}return null}
async function ecb(m){try{return parseCsvLast(await text("https://data-api.ecb.europa.eu/service/data/YC/B.U2.EUR.4F.G_N_C.SV_C_YM.SR_"+m+"?lastNObservations=2&format=csvdata"))}catch{return null}}
export default async function handler(req,res){if(req.method==="OPTIONS")return res.status(204).end();res.setHeader("Cache-Control","s-maxage=300, stale-while-revalidate=900");const pair=String(req.query?.pair||"XAUUSD").toUpperCase();const tasks=await Promise.allSettled([dxy(),treasury("daily_treasury_yield_curve","BC_2YEAR"),treasury("daily_treasury_yield_curve","BC_10YEAR"),treasury("daily_treasury_real_yield_curve","TC_10YEAR"),pair==="EURUSD"?ecb("2Y"):Promise.resolve(null),pair==="EURUSD"?ecb("10Y"):Promise.resolve(null)]);const val=i=>tasks[i].status==="fulfilled"?tasks[i].value:null;const u2=val(1),u10=val(2),e2=val(4),e10=val(5);res.status(200).json({ok:true,pair,dxy:val(0),us2y:u2,us10y:u10,real10y:val(3),eur2y:e2,eur10y:e10,spread2y:e2&&u2?e2.value-u2.value:null,spread10y:e10&&u10?e10.value-u10.value:null,partial:tasks.some(x=>x.status!=="fulfilled")})}